#include "htmstrings.h"

HtmStrings::HtmStrings()
{
	about = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">"
	"<head><title>about</title></head>"
	"<body>"
	"<p><font face=\"Lucida Console\" color=\"#000080\" size=\"5\"><strong>wktools Version 4 - About</strong></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000080\">(c) 2003 - " + WKTOOLSDATE + " by Mathias Spoerr</font></p>"
	"<hr>"
	"<p><font face=\"Lucida Console\" color=\"#000000\" size=\"4\"><strong>General Information:</strong></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Version number: ";
	about += WKTOOLSVERSION;
	about += "</font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">License: Freeware; For the End-User agreement please open the License view</font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Please send questions and bug reports to <a href=\"mailto:wktools@spoerr.org\">wktools@spoerr.org</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Homepage: <a href=\"http://www.spoerr.org/wktools\">http://www.spoerr.org/wktools</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Discussion Forum: <a href=\"http://www.cisco-forum.net/index.php&amp;option=com_smf&amp;Itemid=38&amp;board=17.0\">http://www.cisco-forum.net</a></font></p>"
	"<hr>"
	"<p><font face=\"Lucida Console\" color=\"#000000\" size=\"4\"><strong>Credits:</strong></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Cryptographic support by CRYPTLIB - <a href=\"http://www.cs.auckland.ac.nz/~pgut001/cryptlib/\">http://www.cs.auckland.ac.nz/~pgut001/cryptlib/</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">wxWidgets GUI API - <a href=\"http://www.wxwidgets.org/\">http://www.wxwidgets.org/</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Property Sheet control by Jaakko Salli - <a href=\"http://wxpropgrid.sourceforge.net/cgi-bin/index\">wxPropertyGrid</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">wxWidgets Discussion Forum for forum help - <a href=\"http://wxforum.shadonet.com/\">http://wxforum.shadonet.com/</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Boost Libraries - <a href=\"http://www.boost.org/\">http://www.boost.org/</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">SQLite - <a href=\"http://www.boost.org/\">http://www.boost.org/</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">OGDF Library - <a href=\"http://www.sqlite.org/\">http://www.sqlite.org/</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Hosting of www.spoerr.org by Christian Andergassen</font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Forum - Crispin Ehrling</font></p>"
	"</body>";

	wktools = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">"
	"<html>"
	"<head><title>wktools</title></head>"
	"<body>"
	"<p><font face=\"Lucida Console\" color=\"#000080\" size=\"6\"><strong>wktools Version 4 (" + WKTOOLSVERSION + ")</strong></font></p>"
	"<p><font face=\"Lucida Console\" size=\"2\">(C) 2003 - " + WKTOOLSDATE + " by Mathias Spoerr</font></p>"
	"<hr>"
	"<p><font face=\"Lucida Console\" color=\"#000080\">Latest versions, Documentation and Tutorials are available at <a href=\"http://www.spoerr.org/wktools/\">wktools3 Home</a></font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000080\">A discussion forum for support and questions is available at "
	"<a href=\"http://www.cisco-forum.net/index.php?option=com_smf&amp;Itemid=38&amp;board=17.0;language=english\">www.cisco-forum.net</a></font></p>"
	"<br>"
	"<p><font face=\"Lucida Console\" color=\"#000080\"><strong>Forum - English version</strong><br>URL: http://www.cisco-forum.net/index.php?option=com_smf&amp;Itemid=38&amp;board=17.0;language=english</font></p>"
	"<p><font face=\"Lucida Console\" color=\"#000080\"><strong>Forum - German version</strong><br>URL: http://www.cisco-forum.net/index.php?option=com_smf&amp;Itemid=38&amp;board=18.0</font></p>"
	"<br><hr><br>"
	"<p><font face=\"Lucida Console\" size=\"4\" color=\"#000080\"><b>HowTo's: </font></p></b><br />"
	"<p><font face=\"Lucida Console\" size=\"4\" color=\"#000080\"><a href=\"http://spoerr.org/wktools/wkeHowTo.html\">Advanced Operations with \"Configure Devices\"</a></font></p><br />"
	"<p><font face=\"Lucida Console\" size=\"4\" color=\"#000080\"><a href=\"http://spoerr.org/wktools/wkmHowTo.html\">How to use wktools to review a Cisco network</a> - (only available in german)</font></p>"
	"<br><hr><br>"
	"<p><font face=\"Lucida Console\" color=\"#000000\">Since Version 3.3.0.0 a Version check is included to wktools."
	"For this check an unencrypted http session is started to www.spoerr.org/wktools"
	"to get the latest version information. No other information is exchanged."
	"</font></p><br><hr><br><br>"
	"<p><font face=\"Lucida Console\" color=\"#008000\"><strong>&lt;&lt;&nbsp; Any feedback is welcome - wktools@spoerr.org&nbsp; &gt;&gt;"
	"</strong></font></p><br>"
	"</body></html>";
}
